### ISSUE TITLE
Invalid Integrate as dependency

### ISSUE THREAD

**Issue by IluhinDotPro** [affise/flutter-sdk#1]
Please change

```yaml
affise_attribution_lib:
    git:
      url: git://github.com/affise/flutter-sdk.git
```

to

```yaml
affise_attribution_lib:
    git:
      url: https://github.com/affise/flutter-sdk.git
```

in Integrate as dependency section
